#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rahoot"
name = "Rahoot"
description.en = "Quiz platform for smaller events"
description.fr = "Plateforme de quiz pour les petits événements"

version = "2.0.2~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
code = "https://github.com/Ralex91/Rahoot"
fund = "https://ko-fi.com/Ralex91"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false # can't be true because of fixed Web Socket port

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Ralex91/Rahoot/archive/refs/tags/2.0.2.tar.gz"
    sha256 = "f077df4896b9ce79bd3581b793e006eee1f3ad428f2ca4c5320e4032b75e3d1a"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]
	main.default = 3001    # Upstream WS need Port 3001
	main.fixed = true
	
    [resources.nodejs]
    version = "22"
