#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------------------------------------------------------
    # EVERYTHING PAST THIS POINT IS OPTIONAL AND MOST LIKELY UNNECESSARY FOR NEW APPS
    #--------------------------------------------------------------------------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    test_upgrade_from.4b31f354947e1cf49e52a9f59a95573a28af37b6.name = "Rahoot"
