#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Not saved by default
ynh_app_setting_set --key=password --value="$password"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

mkdir -p "$install_dir/config"

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template=".env" --destination="$install_dir/config/game.json"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
touch /var/log/$app/$app.log

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building App... This may take quiet some time"

pushd $install_dir
	export CYPRESS_INSTALL_BINARY=0
    ynh_hide_warnings corepack enable && corepack prepare pnpm@10 --activate
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm install
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm run build

    #remove unneeded files
    ynh_hide_warnings ynh_exec_as_app pnpm store prune
    ynh_safe_rm src
    ynh_safe_rm server
    ynh_safe_rm .next/cache
popd

chown -R $app:$app "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"