#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ynh_handle_app_migration
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MIGRATE FROM RAHOOT TO RAZZIA
#=================================================
ynh_app_migration_migrate --migration_id="rahoot" --migration_list="migration_list"

if [ $migration_process -eq 1 ]
then

	# If a migration has been perform
	# Reload some values changed by the migration process
	install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)

	ynh_script_progression "Making sure dedicated system user exists..."

	# Create a dedicated user (if not existing)
	ynh_system_user_create --username=$app --home_dir="$install_dir"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

mkdir -p "$install_dir/config"

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="game.json" --destination="$install_dir/config/game.json"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
touch /var/log/$app/$app.log


#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building App... This may take quiet some time"

pushd $install_dir
	export CYPRESS_INSTALL_BINARY=0
    ynh_hide_warnings corepack enable && corepack prepare pnpm@10 --activate
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm install
    ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm run build

    #remove unneeded files
    ynh_hide_warnings ynh_exec_as_app pnpm store prune
popd

chown -R $app:www-data "$install_dir"


ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

#=================================================
# FINISH MIGRATION PROCESS
#=================================================


if [ $migration_process -eq 1 ]
then
	ynh_app_migration_post_migrate
fi


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"